name: marcusng_todo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  intl: ^0.16.1
  sqflite: ^1.3.0
  path_provider: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
